# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
  
  Anime.create(name: 'Cowboy Bebop', image: 'http://animeshow.tv/images/series/Cowboy-Bebop.jpg', genre: 'Action', description: 'Enter a world in the distant future, where Bounty Hunters roam the solar system. Spike and Jet, bounty hunting partners, set out on journeys in an ever struggling effort to win bounty rewards to survive.<br><br>\nWhile traveling, they meet up with other very interesting people. Could Faye, the beautiful and ridiculously poor gambler, Edward, the computer genius, and Ein, the engineered dog be a good addition to the group?')
  
  Anime.create(name: 'Dragonball', image: 'http://animeshow.tv/images/series/Dragon-Ball.jpg', genre: 'Action', description: 'Bulma is a girl in search of the mystical dragonballs that when brought together grant any wish. In her search she bumps into the owner of one of these balls, a strange boy named Goku. The two then set off together, Bulma in search of the dragonballs and Goku on a quest to become stronger.')
  
  Anime.create(name: 'Black Lagoon', image: 'http://animeshow.tv/images/series/Black-Lagoon.jpg', genre: 'Action', description: 'Okajima Rokuro is a Japanese businessman in a town full of Japanese businessmen. His normal day consists of social drinking with clients and being kicked around by his bosses. He finally gets a break though, as he is sent by his company to the tropical seas of Eastern China to deliver a disk. But his boat gets hijacked by a band of mercenaries hired to retrieve the disc. Rock (as he is newly dubbed by his captors) catches the interest of the only female merc Revy as she thinks he is worth a ransom, taking him hostage. However, the disc that was stolen has a terrible secret that is unknown to Rock, which causes massive confusion and chaos for both him and his kidnappers.')
  
  Anime.create(name: 'Clannad', image: 'http://animeshow.tv/images/series/Clannad.jpg', genre: 'Drama', description: 'A high school boy developing a friendship with five girls.')
  
  Anime.create(name: 'Angel Beats', image: 'http://animeshow.tv/images/series/Angel-Beats.jpg', genre: 'Drama', description: 'Otonashi awakens only to learn he is dead. A rifle-toting girl named Yuri explains that they are in the afterlife, and Otonashi realizes the only thing he can remember about himself is his name. Yuri tells him that she leads the Shinda Sekai Sensen (Afterlife Battlefront) and wages war against a girl named Tenshi. Unable to believe Yuri\'s claims that Tenshi is evil, Otonashi attempts to speak with her, but the encounter doesn\'t go as he intended. Otonashi decides to join the SSS and battle Tenshi, but he finds himself oddly drawn to her. While trying to regain his memories and understand Tenshi, he gradually unravels the mysteries of the afterlife.')
  
  Anime.create(name: 'Parasyte: The Maxim', image: 'http://animeshow.tv/images/series/Kiseijuu-Sei-no-Kakuritsu.jpg', genre: 'Sci-fi', description: 'Based on Iwaaki Hitoshi\'s science-fiction horror manga by the same name. The 17-year-old Izumi Shinichi lives with his mother and father in a quiet neighborhood in Tokyo. One night, worm-like aliens called Parasytes invade Earth, taking over the brains of human hosts by entering through their ears or noses. One Parasyte attempts to crawl into Shinichi\'s ear while he sleeps, but fails since he is wearing headphones, and enters his body by burrowing into his arm instead, taking over his right hand and is named Migi. Because Shinichi was able to prevent Migi from traveling further up into his brain, both beings retain their separate intellect and personality. As the duo encounter other Parasytes, they capitalize on their strange situation and gradually form a strong bond, working together to survive. This gives them an edge in battling other Parasytes, who frequently attack the pair upon realization that Shinichi\'s human brain is still intact. Shinichi feels compelled to fight other Parasytes, who devour humans as food, while enlisting Migi\'s help.')
  
  Anime.create(name: 'Death Parade', image: 'http://animeshow.tv/images/series/Death-Parade.jpg', genre: 'Sci-fi', description: 'After death, humans are either sent to the void or reincarnated. But for some, at the instant of their death, they arrive at Quindecim, a bar attended by the mysterious white-haired Decim. He challenges them to the Death Game, wherein they wager their lives and reveal their true natures. Decim himself is the ultimate arbitrator of who wins and who loses, who will go to the void, and who will be reincarnated.')
  
  Anime.create(name: 'My Love Story', image: 'http://animeshow.tv/images/series/Ore-Monogatari.jpg', genre: 'Romance', description: 'Gouda Takeo is a freshman in high school. (Both estimates) Weight: 120kg, Height: 2 meters. He spends his days peacefully with his super-popular-with-girls, yet insensitive childhood friend, Sunakawa. One morning, on the train to school, Takeo saves a girl, Yamato, from being molested by a pervert. Could this be the beginning of spring for Takeo?')
  
  Anime.create(name: 'Say I Love You', image: 'http://animeshow.tv/images/series/Sukitte-Ii-na-yo.jpg', genre: 'Romance', description: 'Friends suck, and trusting someone is just setting yourself up. That\'s the lesson Mei Tachibana learned after her heart was ripped out and only a shell was left where a girl used to be. But unlike so many, she found an easy solution: she\'ll never make another friend. Ever.
Okay, maybe that\'s not as easy as it sounds, but it\'s worked for Mei - or at least, it did until handsome, charming and annoyingly popular Yamato Kurosawa came along. For some freakish reason, he seems to like Mei. He even gave her his phone number! As if she would ever call him. Except she did. But only because she needed help. Still, he came. He actually came. And now things are getting way too complicated.
Mei\'s no princess in a tower. She\'s not waiting for a knight in shining armor to rescue her. So why did he have to kiss her and confuse everything? And why are those three little words so hard to say?')
  
  Anime.create(name: 'Akame Ga Kill!', image: 'http://animeshow.tv/images/series/Akame-ga-Kill.jpg', genre: 'Adventure', description: 'In a fantasy world, fighter Tatsumi sets out for the Capitol to earn money for his starving village, and finds a world of unimaginable corruption, all spreading from the depraved Prime Minister who controls the child Emperor\'s ear. After nearly becoming a victim of this corruption himself, Tatsumi is recruited by Night Raid, a group of assassins dedicated to eliminating the corruption plaguing the Capitol by mercilessly killing those responsible.')
  
  Anime.create(name: 'Hunter X Hunter 2011', image: 'http://animeshow.tv/images/series/hunter-x-hunter-2011.jpg', genre: 'Adventure', description: 'A new adaptation of the the manga series by Togashi Yoshihiro. A Hunter is one who travels the world doing all sorts of dangerous tasks. From capturing criminals to searching deep within uncharted lands for any lost treasures. Gon is a young boy whose father disappeared long ago, being a Hunter. He believes if he could also follow his father\'s path, he could one day reunite with him. After becoming 12, Gon leaves his home and takes on the task of entering the Hunter exam, notorious for its low success rate and high probability of death to become an official Hunter. He befriends the revenge-driven Kurapika, the doctor-to-be Leorio and the rebellious ex-assassin Killua in the exam, with their friendship prevailing throughout the many trials and threats they come upon taking on the dangerous career of a Hunter.')
  
  Anime.create(name: 'Azumanga Daioh', image: 'http://cdn.myanimelist.net/images/anime/1/66.jpg', genre: 'Comedy', description: 'Azumanga Daioh is about high school life through the eyes of six girls with unusual personalities: Chiyo (the 10-year-old genius), Osaka (the resident airhead), Sakaki (the shy one prone to cat bites), Tomo (the loose cannon), Yomi (the short-tempered one) and Kagura (the resident jock).')
  
  Anime.create(name: 'FLCL', genre: 'Comedy', image: 'http://cdn.myanimelist.net/images/anime/6/5389.jpg', description: 'Naota is normal Japanese 6th grade boy, but when his older brother leaves for America to play baseball, his brother leaves his homeless 17-year-old girlfriend Mamimi behind, Mamimi is sending mixed signals and advances to Naota, and he doesn\'t know what to do about her. But to make matters worse, Naota\'s world is totally upside down when is run over by a woman on a Vepsa. During their first encounter, she hits him over the head with her bass guitar, which then causes a horn to grow out of his forehead. She calls herself "Haruko" and her presence changes Naota\'s life to even further insanity.')